config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get "followed"
      get "follower"
    end
  end

  resources :books do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  resources :relationships, only: [:create,:destroy]
  #post ":user_id/relationships", to:"relationships#create",as:"relationships"
  #delete ":user_id/relationship", to:"relationships#destroy",as:"relationship"
  root 'homes#top'
  get 'home/about' => 'homes#about'

  get "search" => "search#search"

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @model = params["search"]["model"]
    @datas = search_for(@how,@model,@content)
  end

  private

    def perfect_match(model,content)
      if model == "user"
        User.where(name: content)
      elsif model == "book"
        Book.where(title: content)
      end
    end

    def forward_match(model,content)
      if model == "user"
        User.where("name Like ?","#{content}%")
      elsif model == "book"
        Book.where("title Like ?","#{content}%")
      end
    end

    def backward_match(model,content)
      if model == "user"
        User.where("name Like ?","%#{content}")
      elsif model == "book"
        Book.where("title Like ?","%#{content}")
      end
    end

    def partical_match(model,content)
      if model == "user"
        User.where("name Like ?","%#{content}%")
      elsif model == "book"
        Book.where("title Like ?","%#{content}%")
      end
    end

    def search_for(how,model,content)
      case how
      when "perfect_match"
        perfect_match(model,content)
      when "forward_match"
        forward_match(model,content)
      when "backward_match"
        backward_match(model,content)
      when "partical_match"
        partical_match(model,content)
      end
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class = "container">
  <% if @model == "user" %>
    <h2>Users search for"<%= @content %>"</h2>
    <div class = "row justify-content-center" >
      <table class = "table">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Introducion</th>
          </tr>
        </thead>
        <% @datas.each do |datas| %>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag datas,:profile_image,:fill,50,50,format: "jpg",fallback: "no-image-icon.jpg" %>
              </td>
              <td>
                <%= link_to datas.name,user_path(datas.id) %>
              </td>
              <td>
                <%= datas.introduction %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>

  <% else %>
    <h2>Books search for"<%= @content %>"</h2>
    <div class = "row justify-content-center" >
      <table class = "table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @datas.each do |datas| %>
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag datas.user,:profile_image,:fill,50,50,format: "jpg",fallback: "no-image-icon.jpg" %>    
              </td>
              <td>
                <%= link_to datas.title,book_path(datas.id) %>
              </td>
              <td>
                <%= datas.body %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  <% end %>
</div>