config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get "followed"
      get "follower"
    end
  end

  resources :books do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  resources :relationships, only: [:create,:destroy]
  #post ":user_id/relationships", to:"relationships#create",as:"relationships"
  #delete ":user_id/relationship", to:"relationships#destroy",as:"relationship"
  root 'homes#top'
  get 'home/about' => 'homes#about'

  get "search" => "search#search"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  attachment :profile_image, destroy: false
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy

  has_many :followed_relationships,foreign_key: "follower_id", class_name: "Relationship",dependent: :destroy
  has_many :followeds, through: :followed_relationships
  has_many :follower_relationships,foreign_key: "followed_id", class_name: "Relationship",dependent: :destroy
  has_many :followers, through: :follower_relationships

  def followed?(other_user)
    self.followeds.include?(other_user)
  end

  def follow(other_user)
    self.followed_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    self.followed_relationships.find_by(followed_id: other_user.id).destroy
  end

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def followed
    @user = User.find(params[:id])
    @followeds = @user.followeds
  end

  def follower
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><p>フォロー数：<%= user.followeds.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
<% unless params[:controller] == "users" && params[:action] == "followed" %>
<% unless params[:controller] == "users" && params[:action] == "follower" %>
        <td><% unless current_user == user %>
              <% if current_user.followed?(user) %>
                <%= link_to "フォロー外す", relationship_path(user,relationship: { followed_id: user.id }), method: :delete %>
              <% else %>
                <%= link_to "フォローする", relationships_path(relationship: { followed_id: user.id }), method: :post %>
              <% end %>
            <% end %></td>
<% end %>
<% end %>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user,:profile_image,:fill, 100, 100,format: "jpeg", fallback: "no-image-icon.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to followed_user_path(user) do %>
          <%= user.followeds.count %>
        <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to follower_user_path(user) do %>
          <%= user.followers.count %>
        <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% unless current_user == user %>
  <% if current_user.followed?(user) %>
    <%= form_with(model: current_user.followed_relationships.find_by(followed_id: user.id),method: :delete,local: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォローを外す",class: "btn btn-success" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.followed_relationships.build,local: true) do |f| %>
      <%= f.hidden_field :followed_id, value: user.id %>
      <%= f.submit "フォローをする",class: "btn btn-success" %>
    <% end %>
  <% end %>
  <% else %>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followed.html.erb
<h2>Follow Users</h2>
<% if @user.followeds.count == 0 %>
 <p>メンバーがいません</p>
 <% else %>
<%= render 'index', users: @followeds %>
<% end %>

app/views/users/follower.html.erb
<h2>Follower Users</h2>
<% if @user.followers.count == 0 %>
  <p>メンバーがいません</p>
<% else %>
  <%= render 'index', users: @followers %>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render "layouts/errors",obj: @book %>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render "layouts/errors",obj: @book %>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>