config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get "followed"
      get "follower"
    end
  end

  resources :books do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments,only: [:create,:destroy]
  end
  resources :relationships, only: [:create,:destroy]
  #post ":user_id/relationships", to:"relationships#create",as:"relationships"
  #delete ":user_id/relationship", to:"relationships#destroy",as:"relationship"
  root 'homes#top'
  get 'home/about' => 'homes#about'

  get "search" => "search#search"

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments,dependent: :destroy
	has_many :favorites,dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <label for= "title">Title</label>
    <%= f.text_field :title,id:"title", class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <label for="opinion">Opinion</label>
    <%= f.text_area :body,id:"opinion", class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <% if controller_name == "books" %>
        <td class = "favorite-btn-<%= book.id.to_s %>">
          <%= render "favorites/favorite-btn",book: book %>
          <%# if book.favorited_by?(current_user) %>
          <!--<p>-->
            <%#= link_to book_favorites_path(book), method: :delete do %>
              <!--♥<%#= book.favorites.count %>-->
            <%# end %>
          <!--</p>-->
        <%# else %>
        <!--<p>-->
          <%#= link_to book_favorites_path(book), method: :post do %>
            <!--♡<%#= book.favorites.count %>-->
          <%# end %>
        <!--</p>-->
          <%# end %>
          </td>
        <% end %>
        <td><p>コメント数：<%= book.book_comments.count %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render "layouts/errors",obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render "layouts/errors",obj: @book %>
      <%= render "layouts/errors",obj: @book_comment %>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100,format: "jpeg", fallback: "no-image-icon.jpg" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
          <% if controller_name == "books" %>
            <td class = "favorite-btn">
              <%= render "favorites/favorite-btn",book: @book %>
              <%# if @book.favorited_by?(current_user) %>
                <!--<p>-->
                  <%#= link_to book_favorites_path(@book), method: :delete do %>
                    <!--♥<%#= @book.favorites.count %>-->
                  <%# end %>
                <!--</p>-->
                <%# else %>
                <!--<p>-->
                  <%#= link_to book_favorites_path(@book), method: :post do %>
                    <!--♡<%#= @book.favorites.count %>-->
                  <%# end %>
                <!--</p>-->
              <%# end %>
            </td>
          <% end %>
          <td><p>コメント数：<%= @book.book_comments.count %></p></td>
        </tr>
      </table>
      <div class = "comment-space">
        <%= render "book_comments/book_comments",book: @book %>
        <!--<div class="comments">-->
          <%# @book.book_comments.each do |book_comment| %>
              <%#= attachment_image_tag @book.user, :profile_image, :fill, 100, 100,format: "jpeg", fallback: "no-image-icon.jpg" %>
            <%#= book_comment.comment %>
            <%# if current_user == book_comment.user %>
              <%#= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment),method: :delete,class: "btn btn-danger" %>
            <%# end %>
            <!--<br>-->
            <%#= @book.user.name %>
          <%# end %>
        <!--</div>-->
        <!--<div class = "form-group">-->
          <%#= form_with(model:[@book,@book_comment],local: true) do |f| %>
            <%#= f.text_area :comment,rows:"5",placeholder:"コメントをここに",class: "form-control" %>
            <%#= f.submit "送信" %>
          <%# end %>
        <!--</div>-->
      </div>
    </div>
  </div>
</div>